// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"dogker/lintang/monitor-service/internal/repository/postgres"
	"dogker/lintang/monitor-service/internal/rest"
	"dogker/lintang/monitor-service/monitor"
	"dogker/lintang/monitor-service/pkg/gorm"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitRouterApi(gormGorm *gorm.Gorm, engine *gin.Engine) *gin.RouterGroup {
	containerRepository := postgres.NewContainerRepo(gormGorm)
	service := monitor.NewService(containerRepository)
	routerGroup := rest.NewRouter(engine, service)
	return routerGroup
}

// wire.go:

// var ProviderSet = wire.NewSet(gorm.NewGorm)
var monitorSet = wire.NewSet(postgres.NewContainerRepo, monitor.NewService, wire.Bind(new(monitor.ContainerRepository), new(*postgres.ContainerRepository)), wire.Bind(new(rest.MonitorService), new(*monitor.Service)))
